// Dependency-free browser smoke test using Chrome's DevTools protocol.
import {spawn} from "node:child_process";
import http from "node:http";
import {readFile,mkdtemp,rm,mkdir,writeFile} from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import assert from "node:assert/strict";
import {createCompanion} from "../companion/server.mjs";
const root=path.resolve(import.meta.dirname,".."), profile=await mkdtemp(path.join(os.tmpdir(),"mlgm-chrome-"));
const server=http.createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;const base=pathname.startsWith('/foundry/')?path.resolve(process.env.FOUNDRY_PUBLIC||'E:/Foundry14/App/resources/app/public'):pathname.startsWith('/modules/morelord-core/')?path.resolve(root,'../morelord-core'):root;const route=pathname.startsWith('/foundry/')?pathname.slice('/foundry'.length):base===root?pathname:pathname.slice('/modules/morelord-core'.length);const p=path.resolve(base,`.${route}`);if(!p.startsWith(base+path.sep))throw Error();res.setHeader('Content-Type',p.endsWith('.html')?'text/html':p.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(p));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const companion=createCompanion({directory:path.join(profile,'campaign-data'),origins:[`http://127.0.0.1:${server.address().port}`],apiKey:'test-only',model:'test-model',fetchImpl:async()=>Response.json({status:'completed',output:[{content:[{type:'output_text',text:'Test answer from the campaign document.'}]}]})});
await new Promise(r=>companion.server.listen(0,'127.0.0.1',r));
const chrome=spawn(process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
let socket;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
try {
  let port;
  for(let i=0;i<100;i++){try{port=(await readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];break;}catch{await delay(100);}}
  if(!port)throw Error('Chrome did not start. Set CHROME_PATH to a Chrome/Edge executable.');
  let targets;
  for(let i=0;i<15;i++){try{targets=await(await fetch(`http://127.0.0.1:${port}/json/list`,{signal:AbortSignal.timeout(1000)})).json();if(targets.length)break;}catch{}await delay(100);}
  if(!targets?.length)throw Error('Chrome debugging endpoint did not become available.');
  socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});
  let serial=0;const pending=new Map(),errors=[];
  socket.onmessage=({data})=>{const m=JSON.parse(data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);if(m.error)p.reject(Error(m.error.message));else p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);};
  const command=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const r=await command('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true,replMode:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
  const wait=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await delay(50);}throw Error(`Timed out: ${expression}\n${errors.join('\n')}\n${await evaluate('location.href + " " + document.body.innerText.slice(0,1200)')}`);};
  const click=async selector=>{await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await delay(75);};
  await command('Runtime.enable');await command('Page.enable');
  await command('Emulation.setDeviceMetricsOverride',{width:1280,height:850,deviceScaleFactor:1,mobile:false});
  await command('Page.navigate',{url:`http://127.0.0.1:${server.address().port}/tests/harness.html`});await wait('window.testReady');
  await click('[data-action="toggle"]');assert.equal(await evaluate('testState().hotbar'),'none');
  assert.equal(await evaluate('document.querySelector(".gm-tray").getBoundingClientRect().height>=innerHeight*.5'),true);
  assert.equal(await evaluate('!!document.querySelector("#mlgm footer")'),false);
  assert.equal(await evaluate('document.querySelectorAll("[data-roll-card] input[name=blind]:checked").length'),0);
  await evaluate('var blind=document.querySelector("[data-roll-card=group] input[name=blind]");blind.checked=true;blind.dispatchEvent(new Event("change",{bubbles:true}))');
  await wait('testState().board.last.group?.blind===true');

  await click('[data-action="card-save"][data-id="group"]');await wait('testState().board.saved.length===1');
  assert.equal(await evaluate('document.querySelectorAll(".gm-roll-column")[1].querySelectorAll("form strong")[1].textContent'),'Perception Check');
  await click('[data-action="card-roll"][data-id="group"]');await wait('game.messages.size===1');assert.equal(await evaluate('!!document.querySelector("dialog")'),false);
  await click('[data-mlgm-actor="actor0"][data-mlgm-mode="normal"]');await wait('game.messages.size===2');
  assert.equal(await evaluate('game.messages.some(m=>m.getFlag("morelord-game-master","summary"))'),false);
  await click('[data-mlgm-actor="actor1"][data-mlgm-mode="normal"]');await click('[data-mlgm-actor="actor2"][data-mlgm-mode="normal"]');await wait('game.messages.size===5');
  assert.match(await evaluate('game.messages.find(m=>m.getFlag("morelord-game-master","summary"))?.content'),/Average: 11.00/);
  assert.doesNotMatch(await evaluate('document.querySelector("#mlgm-panel").textContent'),/Average|received/);
  assert.equal(await evaluate('!!document.querySelector("[data-roll-card=player] select[name=actorId]")'),true);
  await click('[data-action="card-save"][data-id="player"]');await wait('testState().board.saved.length===2');
  await evaluate('var die=document.querySelector("[data-roll-card=encounter] select[name=die]");die.value="12";die.dispatchEvent(new Event("change",{bubbles:true}))');
  await wait('testState().board.last.encounter?.die===12');
  await evaluate('var blind=document.querySelector("[data-roll-card=encounter] input[name=blind]");blind.checked=false;blind.dispatchEvent(new Event("change",{bubbles:true}))');
  await wait('testState().board.last.encounter?.blind===false');
  await click('[data-action="card-roll"][data-id="encounter"]');await wait('game.messages.size===6');
  await click('[data-action="tab"][data-id="party"]');
  await evaluate('var choice=document.querySelectorAll("input[name=actorUuids]")[2];choice.checked=false;choice.dispatchEvent(new Event("change",{bubbles:true}))');
  await wait('testState().board.partyActorIds?.length===2');
  await click('[data-action="tab"][data-id="rolls"]');
  assert.equal(await evaluate('document.querySelector("[data-roll-card=encounter] select[name=die]").value'),'12');
  assert.equal(await evaluate('document.querySelector("[data-roll-card=group] input[name=blind]").checked'),true);
  assert.equal(await evaluate('document.querySelector("[data-roll-card=encounter] input[name=blind]").checked'),false);
  assert.equal(await evaluate('document.querySelector("#mlgm-panel").classList.contains("ml-surface")'),false);
  await click('[data-action="tab"][data-id="macros"]');assert.equal(await evaluate('document.querySelectorAll("[data-macro-uuid]").length'),0);
  await evaluate('var transfer=new DataTransfer();transfer.setData("text/plain",JSON.stringify({type:"Macro",uuid:"Macro.macro"}));document.querySelector("#mlgm-panel").dispatchEvent(new DragEvent("drop",{bubbles:true,dataTransfer:transfer}))');await wait('document.querySelectorAll("[data-macro-uuid]").length===1');
  await click('[data-action="macro"]');assert.equal(await evaluate('testState().macroRuns'),1);
  for(let i=0;i<11;i++) {
    await evaluate(`game.macros.set('extra${i}',{id:'extra${i}',uuid:'Macro.extra${i}',name:'Extra ${i}',canExecute:true,img:'icons/svg/dice-target.svg'});var transfer=new DataTransfer();transfer.setData('text/plain',JSON.stringify({type:'Macro',uuid:'Macro.extra${i}'}));document.querySelector('#mlgm-panel').dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:transfer}))`);
    await wait(`document.querySelectorAll('[data-macro-uuid]').length===${i+2}`);
  }
  assert.equal(await evaluate('document.querySelectorAll("[data-macro-uuid]").length'),12);
  await evaluate('document.querySelector("[data-macro-uuid]").dispatchEvent(new MouseEvent("contextmenu",{bubbles:true}))');await click('#context-menu button');assert.equal(await evaluate('game.macros.has("macro")'),true);
  await evaluate('var music=game.playlists.get("music");music.mode=-1;var oldSound={id:"old",playing:true};game.playlists.set("old",{id:"old",name:"Previous music",getFlag:()=>false,sounds:new game.playlists.constructor([["old",oldSound]]),async stopAll(){oldSound.playing=false;}})');
  await click('[data-action="tab"][data-id="sound"]');await click('[data-action="playlist"]');await click('dialog button[value="0"]');await wait('testState().board.saved.some(s=>s.type==="playlist")');
  assert.equal(await evaluate('game.playlists.get("music").sounds.get("sound").playing'),false);
  await click('[data-action="saved"]');await wait('game.playlists.get("music").sounds.get("sound").playing');
  assert.equal(await evaluate('game.playlists.get("music").mode'),1);assert.equal(await evaluate('oldSound.playing'),false);
  assert.equal(await evaluate('document.querySelector("[data-action=stop-music]").closest(".gm-column").querySelector("strong").textContent'),'Now Playing');
  await click('[data-action="stop-music"]');assert.equal(await evaluate('!!document.querySelector("[data-action=stop-music]")'),false);
  await evaluate('await game.modules.get("morelord-game-master").api.addTrigger({name:"Wild Magic",actorId:"actor0",itemId:"spell",tableId:"table"})');
  await evaluate('var cfg={data:{}};Hooks.callAll("dnd5e.preCreateUsageMessage",{actor:game.actors.get("actor0"),item:{id:"spell"}},cfg);await ChatMessage.create({...cfg.data,speaker:{actor:"actor0"}})');await wait('window.tableDraws===1');
  await click('[data-action="tab"][data-id="triggers"]');await click('[data-action=trigger-toggle]');assert.equal(await evaluate('testState().board.triggers[0].enabled'),false);
  await click('[data-action="new-trigger"]');await click('dialog button[value="0"]');
  assert.equal(await evaluate('document.querySelector("dialog input[name=gameMinutes]").value'),'10');
  assert.equal(await evaluate('document.querySelector("dialog input[name=realMinutes]").value'),'1');
  await evaluate('document.querySelector("dialog input[name=gameMinutes]").value="5";document.querySelector("dialog input[name=realMinutes]").value="2"');
  await click('dialog button[value="0"]');await wait('testState().board.triggers.some(t=>t.kind==="world-clock")');
  assert.equal(await evaluate('window.globalTriggerFile.triggers.find(t=>t.kind==="world-clock").gameMinutes'),5);
  await evaluate('var clockID=testState().board.triggers.find(t=>t.kind==="world-clock").id');
  await evaluate(`document.querySelector('[data-action="trigger-edit"][data-id="'+clockID+'"]').click()`);
  await click('dialog button[value="0"]');assert.equal(await evaluate('document.querySelector("dialog input[name=realMinutes]").value'),'2');
  await click('dialog button[value="0"]');
  const clockShot=await command('Page.captureScreenshot',{format:'png'});await writeFile(path.join(root,'test-results','world-clock.png'),Buffer.from(clockShot.data,'base64'));
  await evaluate(`document.querySelector('[data-action="trigger-toggle"][data-id="'+clockID+'"]').click()`);
  await click('[data-action="tab"][data-id="ai"]');assert.equal(await evaluate('document.querySelector("[data-action=ai-send]").disabled'),true);
  await evaluate('new (game.settings.menus.get("morelord-game-master.configure").type)().render()');
  await evaluate(`document.querySelector('dialog input[name=url]').value='http://127.0.0.1:${companion.server.address().port}';document.querySelector('dialog input[name=token]').value='${companion.token}'`);
  await click('dialog button[value="0"]');await click('[data-action="ai-connect"]');await wait('!document.querySelector("[data-action=ai-create]").disabled');
  await click('[data-action="ai-create"]');await evaluate('document.querySelector("dialog input[name=name]").value="North campaign"');await click('dialog button[value="0"]');await wait('!!document.querySelector("#mlgm-upload")');
  await evaluate('document.querySelector("#mlgm-prompt").value="North draft";document.querySelector("#mlgm-prompt").dispatchEvent(new Event("input",{bubbles:true}))');
  await click('[data-action="ai-create"]');await evaluate('document.querySelector("dialog input[name=name]").value="South campaign"');await click('dialog button[value="0"]');await delay(100);
  assert.equal(await evaluate('document.querySelector("#mlgm-prompt").value'),'');
  await evaluate('var chooser=document.querySelector("#mlgm-campaign");chooser.value=[...chooser.options].find(o=>o.text==="North campaign").value;chooser.dispatchEvent(new Event("change",{bubbles:true}))');await wait('document.querySelector("#mlgm-prompt").value==="North draft"');
  const uploadPath=path.join(profile,'notes.txt');await writeFile(uploadPath,'The tower is north.');
  const dom=await command('DOM.getDocument'),fileInput=await command('DOM.querySelector',{nodeId:dom.root.nodeId,selector:'#mlgm-upload'});
  await command('DOM.setFileInputFiles',{nodeId:fileInput.nodeId,files:[uploadPath]});await wait('document.querySelector("#mlgm-panel").textContent.includes("notes.txt")');
  await click('[data-action="ai-send"]');await wait('document.querySelector(".gm-chat").textContent.includes("Test answer")');assert.equal(await evaluate('document.querySelector("#mlgm-prompt").value'),'');
  await mkdir(path.join(root,'test-results'),{recursive:true});
  const aiShot=await command('Page.captureScreenshot',{format:'png'});await writeFile(path.join(root,'test-results','campaign-ai.png'),Buffer.from(aiShot.data,'base64'));
  await click('[data-action="ai-remove-file"]');await wait('!document.querySelector("#mlgm-panel").textContent.includes("notes.txt")');
  await click('[data-action="tab"][data-id="rolls"]');
  const scrollReport=await evaluate('var {checkScrollPreservation}=await import("/tests/scroll-regression.mjs");await checkScrollPreservation()');
  console.log(JSON.stringify({offlineScroll:scrollReport}));
  await mkdir(path.join(root,'test-results'),{recursive:true});
  const shot=await command('Page.captureScreenshot',{format:'png'});await writeFile(path.join(root,'test-results','tray-desktop.png'),Buffer.from(shot.data,'base64'));
  await command('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});
  assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'),true);
  const mobile=await command('Page.captureScreenshot',{format:'png'});await writeFile(path.join(root,'test-results','tray-mobile.png'),Buffer.from(mobile.data,'base64'));
  await click('[data-action="remove-saved"]');assert.equal(await evaluate('testState().board.saved.some(s=>s.type==="group")'),false);

  await click('[data-action="toggle"]');assert.notEqual(await evaluate('testState().hotbar'),'none');
  await evaluate('document.querySelector("#hotbar").style.display="none"');await click('[data-action="toggle"]');await click('[data-action="toggle"]');assert.equal(await evaluate('testState().hotbar'),'none');
  assert.deepEqual(errors,[]);assert.equal(await evaluate('window.lastError'),undefined);
  console.log('Browser checks passed: requests, real-handler roll results, duplicate guard, chat-only results, saved checks, scenarios, macros, playlist controls, trigger activation/pause, authenticated companion, campaign creation/switching, draft isolation, file upload/removal, chat, narrow layout, and hotbar restoration.');
  console.log('Screenshots: test-results/tray-desktop.png and tray-mobile.png. Foundry APIs are mocked in this harness.');
} finally {
  socket?.close();chrome.kill();await new Promise(r=>server.close(r));await new Promise(r=>companion.server.close(r));
  await delay(500);await rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:200});
}
