import test from 'node:test';
import assert from 'node:assert/strict';
import {huntersMarkHit,executeTrigger} from '../scripts/triggers.mjs';
const ID='morelord-game-master';
test('Hunter’s Mark uses native damage, caster-owned active marks, kept critical dice, and one result per attack',async()=>{
  const gm={id:'gm',isGM:true},messages=[],configs=[];
  const activity={type:'damage',messageSources:{},getDamageConfig:config=>{configs.push(config);return {rolls:[{options:{type:'force'},data:{roll:{damage:{type:'force'}}}}]};}};
  const mark={uuid:'Actor.a.Item.mark',system:{identifier:'hunters-mark',source:{rules:'2024'},activities:[activity]}};
  const weapon={id:'weapon',type:'weapon',system:{damage:{base:{types:new Set(['piercing'])}}}};
  const items=[weapon,mark];items.get=id=>items.find(i=>i.id===id);
  const actor={id:'a',type:'character',name:'Ranger',items,concentration:{items:new Set([mark])}};
  const effect={active:true,origin:mark.uuid},target={ac:15,token:'Scene.s.Token.t'};
  globalThis.fromUuidSync=()=>({actor:{appliedEffects:[effect]}});
  globalThis.game={actors:new Map([['a',actor]]),users:[gm],messages,combat:{started:true,id:'combat',round:1,turn:0}};
  globalThis.ChatMessage={getSpeaker:({actor})=>({actor:actor.id}),create:async data=>messages.push({...data,getFlag:(ns,key)=>data.flags?.[ns]?.[key]})};
  globalThis.CONFIG={Dice:{DamageRoll:{build:async config=>{assert.equal(config.subject,activity);return [{total:4,options:config.rolls[0].options}];}}}};
  const attack={id:'attack',type:'attack',speaker:{actor:'a'},author:gm,system:{item:{id:'weapon'},targets:[target]},rolls:[{total:18,dice:[{faces:20,results:[{result:20,active:false},{result:12,active:true}]}]}],getFlag:()=>null,setFlag:async()=>{}};
  assert.equal(huntersMarkHit(attack,actor,weapon).critical,false);
  effect.active=false;assert.equal(huntersMarkHit(attack,actor,weapon),null);effect.active=true;
  effect.origin='Actor.other.Item.mark';assert.equal(huntersMarkHit(attack,actor,weapon),null);effect.origin=mark.uuid+'.Activity.cast';
  actor.concentration.items.clear();assert.equal(huntersMarkHit(attack,actor,weapon),null);actor.concentration.items.add(mark);
  attack.rolls[0].total=14;assert.equal(huntersMarkHit(attack,actor,weapon),null);attack.rolls[0].total=18;
  attack.rolls[0].isFumble=true;assert.equal(huntersMarkHit(attack,actor,weapon),null);attack.rolls[0].isFumble=false;
  mark.system.source.rules='2014';assert.equal(huntersMarkHit(attack,actor,{type:'spell'}),null);mark.system.source.rules='2024';assert.ok(huntersMarkHit(attack,actor,{type:'spell'}));
  // Native D&D5e 6 retains the compendium origin and records the caster separately.
  effect.origin='Compendium.dnd-players-handbook.spells.Item.phbsplHuntersMar';
  effect.system={origin:{activity:mark.uuid+'.Activity.cast'}};
  assert.ok(huntersMarkHit(attack,actor,weapon));
  effect.system.origin.activity='Actor.other.Item.mark.Activity.cast';assert.equal(huntersMarkHit(attack,actor,weapon),null);
  effect.system.origin.activity=mark.uuid+'.Activity.cast';
  const damage={type:'damage',rolls:[{total:7}],speaker:attack.speaker,system:attack.system,getFlag:()=>null,getOriginatingMessage:()=>attack};
  const trigger={id:'mark-rule',kind:'hunters-mark'};
  assert.equal(await executeTrigger(trigger,attack),false);
  assert.equal(await executeTrigger(trigger,damage),true);assert.equal(configs[0].isCritical,false);
  assert.equal(await executeTrigger({...trigger,id:'another-rule'},damage),false);
  assert.equal(messages[0].rolls[0].options.type,'force');assert.match(messages[0].flavor,/Hunter&#39;s Mark|Hunter's Mark/);assert.equal(messages[0].blind,true);assert.deepEqual(messages[0].whisper,['gm']);
  attack.id='second-attack';attack.rolls[0].dice[0].results=[{result:20,active:true}];
  assert.equal(await executeTrigger(trigger,damage),true);assert.equal(configs[1].isCritical,true);
  mark.system.source.rules='2014';attack.id='third-attack';
  assert.equal(await executeTrigger(trigger,damage),true);assert.equal(messages[2].rolls[0].options.type,'piercing');
  damage.getFlag=()=>({kind:'hunters-mark'});assert.equal(await executeTrigger(trigger,damage),false);
});
